<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration 3: Add seats.io fields to the bookings table.
 *
 * Your existing bookings table already has all customer, payment, and status
 * fields. We only add the seats.io-specific identifiers needed to:
 *   1. Release the hold if the user abandons checkout
 *   2. Confirm/cancel seats via seats.io API after payment
 *   3. Cross-reference seats.io order in the admin panel
 *
 * New columns:
 *   seatsio_hold_token   — the hold token generated by the seats.io JS widget;
 *                          passed to the server to book specific seats server-side
 *   seatsio_order_id     — ID returned by seats.io after booking is confirmed
 *   booking_mode         — 'general_admission' | 'reserved' | 'mixed'
 *                          (snapshot of show's ticketing_mode at time of booking)
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('bookings', function (Blueprint $table) {

            // Hold token from seats.io JS widget (passed to server at checkout)
            // Must be sent when booking seats via seats.io API
            $table->string('seatsio_hold_token')->nullable()
                  ->after('booking_type')
                  ->comment('Hold token from seats.io JS widget; used to confirm booking via API');

            // seats.io order ID returned after successful booking confirmation
            $table->string('seatsio_order_id')->nullable()
                  ->after('seatsio_hold_token')
                  ->comment('Returned by seats.io after changeObjectStatus(booked) call');

            // Snapshot of ticketing mode at booking time for historical accuracy
            $table->enum('booking_mode', ['general_admission', 'reserved', 'mixed'])
                  ->default('general_admission')
                  ->after('seatsio_order_id')
                  ->comment('Snapshot of show ticketing_mode when booking was created');

            // Index for cleanup jobs that need to release stale holds
            $table->index(['seatsio_hold_token'], 'bookings_seatsio_hold_token_index');
        });
    }

    public function down(): void
    {
        Schema::table('bookings', function (Blueprint $table) {
            $table->dropIndex('bookings_seatsio_hold_token_index');
            $table->dropColumn([
                'seatsio_hold_token',
                'seatsio_order_id',
                'booking_mode',
            ]);
        });
    }
};
