<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration 6: Extend ticket_holds for seats.io hold tokens.
 *
 * Your existing ticket_holds table manages GA quantity holds with session_id.
 * For seats.io, the widget itself manages seat locking (it shows seats as
 * "selected/held" to other users in real time). However, you still need to
 * store the hold_token server-side to:
 *   1. Pass it to the seats.io API when confirming/releasing the booking
 *   2. Allow the cleanup job to release orphaned holds
 *   3. Associate the hold with the user's session or auth token
 *
 * NOTE: For GA shows, your existing session_id / quantity flow is unchanged.
 * For reserved shows, hold_token is the key field; quantity will always be 1
 * (one row per held seat) and seatsio_object_id identifies which seat.
 *
 * New columns:
 *   hold_token          — seats.io hold token (set when widget initialises)
 *   seatsio_object_id   — the specific seat object held by this row
 *   channel_key         — seats.io channel key for multi-channel setups (optional)
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('ticket_holds', function (Blueprint $table) {

            // seats.io hold token — generated by the JS widget on seat selection
            $table->string('hold_token')->nullable()
                  ->after('hold_type')
                  ->comment('Hold token from seats.io JS widget; null for GA holds');

            // The specific seats.io object being held (one row per seat)
            $table->string('seatsio_object_id')->nullable()
                  ->after('hold_token')
                  ->comment('seats.io objectId of the held seat; null for GA holds');

            // Optional: seats.io channel key for isolating holds by sales channel
            $table->string('seatsio_channel_key')->nullable()
                  ->after('seatsio_object_id')
                  ->comment('seats.io channel key (optional multi-channel support)');

            // Index for cleanup queries by hold token
            $table->index(['hold_token'], 'ticket_holds_hold_token_index');
            $table->index(['seatsio_object_id'], 'ticket_holds_seatsio_object_id_index');
        });
    }

    public function down(): void
    {
        Schema::table('ticket_holds', function (Blueprint $table) {
            $table->dropIndex('ticket_holds_hold_token_index');
            $table->dropIndex('ticket_holds_seatsio_object_id_index');
            $table->dropColumn([
                'hold_token',
                'seatsio_object_id',
                'seatsio_channel_key',
            ]);
        });
    }
};
